src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;
use App\Repository\ProductRepository;
use App\Service\ImageEditor\ImageEditorInterface;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("cartService")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Groups("cartService")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Groups("cartService")
     */
    private $price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $forSale;

    /**
     * @ORM\Column(type="integer")
     */
    private $width;

    /**
     * @ORM\Column(type="integer")
     */
    private $height;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Artwork::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("cartService")
     */
    private $artwork;

    /**
     * @ORM\OneToMany(targetEntity=ImageProduct::class, mappedBy="product", orphanRemoval=true, cascade={"persist"})
     * @OrderBy({"disposition" = "ASC"})
     * @Groups("cartService")
     */
    private $imageProducts;

    /**
     * @ORM\Column(type="integer")
     * @Groups("cartService")
     */
    private $stock;

    /**
     * @ORM\ManyToOne(targetEntity=ShopSubCategory::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("cartService")
     */
    private $shopSubCategory;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseItem::class, mappedBy="product", cascade={"remove"})
     */
    private $purchaseItems;

    public function __construct()
    {
        $this->imageProducts = new ArrayCollection();
        $this->purchaseItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getForSale(): ?bool
    {
        return $this->forSale;
    }

    public function setForSale(bool $forSale): self
    {
        $this->forSale = $forSale;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(int $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getArtwork(): ?Artwork
    {
        return $this->artwork;
    }

    public function setArtwork(?Artwork $artwork): self
    {
        $this->artwork = $artwork;

        return $this;
    }

    /**
     * @return Collection|ImageProduct[]
     */
    public function getImageProducts(): Collection
    {
        return $this->imageProducts;
    }

    public function addImageProduct(ImageProduct $imageProduct): self
    {
        if (!$this->imageProducts->contains($imageProduct)) {
            $this->imageProducts[] = $imageProduct;
            $imageProduct->setProduct($this);
        }

        return $this;
    }

    public function removeImageProduct(ImageProduct $imageProduct): self
    {
        if ($this->imageProducts->removeElement($imageProduct)) {
            // set the owning side to null (unless already changed)
            if ($imageProduct->getProduct() === $this) {
                $imageProduct->setProduct(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        $shopCatName = $this->getShopSubCategory()->getShopCategory()->getName();
        $shopSubCatName = $this->getShopSubCategory()->getName();
        $artworkName = $this->getArtwork()->getName();

        return $shopCatName . ' - ' . $shopSubCatName . ' - ' . $artworkName;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getShopSubCategory(): ?ShopSubCategory
    {
        return $this->shopSubCategory;
    }

    public function setShopSubCategory(?ShopSubCategory $shopSubCategory): self
    {
        $this->shopSubCategory = $shopSubCategory;

        return $this;
    }

    /**
     * @return Collection|PurchaseItem[]
     */
    public function getPurchaseItems(): Collection
    {
        return $this->purchaseItems;
    }

    public function addPurchaseItem(PurchaseItem $purchaseItem): self
    {
        if (!$this->purchaseItems->contains($purchaseItem)) {
            $this->purchaseItems[] = $purchaseItem;
            $purchaseItem->setProduct($this);
        }

        return $this;
    }

    public function removePurchaseItem(PurchaseItem $purchaseItem): self
    {
        if ($this->purchaseItems->removeElement($purchaseItem)) {
            // set the owning side to null (unless already changed)
            if ($purchaseItem->getProduct() === $this) {
                $purchaseItem->setProduct(null);
            }
        }

        return $this;
    }

    public function getName(): string
    {
        return $this->__toString();
    }

    public function getFirstImage(): ImageEditorInterface
    {
        $imageProducts = $this->getImageProducts()->first();

        if (!$imageProducts) {
            return $this->getArtwork();
        }

        return $imageProducts;
    }
}

src/Entity/Purchase.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Uid\Uuid;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PurchaseRepository;
use DateTimeImmutable;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PurchaseRepository::class)
 */
class Purchase
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $uuid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $stripeId;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $total;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $purchasedAt;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $trackingNumber;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseItem::class, mappedBy="purchase", orphanRemoval=true, cascade={"persist"})
     */
    private $purchaseItems;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseAddress::class, mappedBy="purchase", orphanRemoval=true, cascade={"persist"})
     */
    private $purchaseAddresses;

    /**
     * @ORM\Column(type="integer")
     */
    private $insuranceCost;

    /**
     * @ORM\Column(type="integer")
     */
    private $weightCost;

    public function __construct()
    {
        $this->purchaseItems = new ArrayCollection();
        $this->purchaseAddresses = new ArrayCollection();
    }

    public const STATUS_ARRAY = [
        0 => "En attente de paiement",
        1 => "En cours de préparation",
        2 => "En cours de livraison",
        3 => "Livré",
        4 => "Annulée",
        5 => "Remboursée"
    ];

    public const PAIEMENT_EN_ATTENTE = self::STATUS_ARRAY[0];
    public const PREPARATION_EN_COURS = self::STATUS_ARRAY[1];
    public const LIVRAISON_EN_COURS = self::STATUS_ARRAY[2];
    public const LIVRE = self::STATUS_ARRAY[3];
    public const ANNULE = self::STATUS_ARRAY[4];
    public const REMBOURSEE = self::STATUS_ARRAY[5];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status)
    {
        if (!in_array($status, self::STATUS_ARRAY)) {
            throw new \InvalidArgumentException("Le statut est invalide.");
        }
        $this->status = $status;

        return $this;
    }

    public static function getEasyAdminStatus(): array
    {
        $array = [];
        foreach (self::STATUS_ARRAY as $value) {
            $array[$value] = $value;
        }
        return $array;
    }

    public function getUuid()
    {
        return $this->uuid;
    }

    // On sauvegarde dans la BDD un UUID en base58
    public function setUuid(): self
    {
        $this->uuid = Uuid::v4()->toBase58();

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->total;
    }

    public function setTotal(?int $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getPurchasedAt(): ?\DateTimeImmutable
    {
        return $this->purchasedAt;
    }

    public function setPurchasedAt(): self
    {
        $this->purchasedAt = new DateTimeImmutable();

        return $this;
    }

    public function getTrackingNumber(): ?string
    {
        return $this->trackingNumber;
    }

    public function setTrackingNumber(?string $trackingNumber): self
    {
        $this->trackingNumber = $trackingNumber;

        return $this;
    }

    /**
     * @return Collection|PurchaseItem[]
     */
    public function getPurchaseItems(): Collection
    {
        return $this->purchaseItems;
    }

    public function addPurchaseItem(PurchaseItem $purchaseItem): self
    {
        if (!$this->purchaseItems->contains($purchaseItem)) {
            $this->purchaseItems[] = $purchaseItem;
            $purchaseItem->setPurchase($this);
        }

        return $this;
    }

    public function removePurchaseItem(PurchaseItem $purchaseItem): self
    {
        if ($this->purchaseItems->removeElement($purchaseItem)) {
            // set the owning side to null (unless already changed)
            if ($purchaseItem->getPurchase() === $this) {
                $purchaseItem->setPurchase(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PurchaseAddress[]
     */
    public function getPurchaseAddresses(): Collection
    {
        return $this->purchaseAddresses;
    }

    public function addPurchaseAddress(PurchaseAddress $purchaseAddress): self
    {
        if (!$this->purchaseAddresses->contains($purchaseAddress)) {
            $this->purchaseAddresses[] = $purchaseAddress;
            $purchaseAddress->setPurchase($this);
        }

        return $this;
    }

    public function removePurchaseAddress(PurchaseAddress $purchaseAddress): self
    {
        if ($this->purchaseAddresses->removeElement($purchaseAddress)) {
            // set the owning side to null (unless already changed)
            if ($purchaseAddress->getPurchase() === $this) {
                $purchaseAddress->setPurchase(null);
            }
        }

        return $this;
    }

    public function getInsuranceCost(): ?int
    {
        return $this->insuranceCost;
    }

    public function setInsuranceCost(int $insuranceCost): self
    {
        $this->insuranceCost = $insuranceCost;

        return $this;
    }

    public function getWeightCost(): ?int
    {
        return $this->weightCost;
    }

    public function setWeightCost(int $weightCost): self
    {
        $this->weightCost = $weightCost;

        return $this;
    }

    public function getStripeId(): ?string
    {
        return $this->stripeId;
    }

    public function setStripeId(string $stripeId): self
    {
        $this->stripeId = $stripeId;

        return $this;
    }

    public function getPdfFilename(): string
    {
        return 'facture-'
            . $this->getPurchasedAt()->format('Y-m-d')
            . '-'
            . $this->getUuid()
            . '-'
            . $this->getStripeId();
    }
}

src/Controller/PurchaseController.php
<?php

namespace App\Controller;

use Stripe\StripeClient;
use App\Entity\Purchase;
use App\Entity\PurchaseItem;
use App\Service\Cart\CartItem;
use App\Service\Cart\CartService;
use App\Form\PurchaseAddressType;
use App\Repository\PurchaseRepository;
use App\Repository\AppSettingsRepository;
use App\Service\PurchaseAddress\PurchaseAddressService;
use App\Service\ShippingCost\ShippingCostService;
use App\Service\Stripe\StripeService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PurchaseController extends AbstractController
{
    public $appSettingsRepo;
    public $purchaseAddressService;
    public $cartService;

    public function __construct(
        AppSettingsRepository $appSettingsRepo,
        PurchaseAddressService $purchaseAddressService,
        CartService $cartService
    ) {
        $this->appSettingsRepo = $appSettingsRepo;
        $this->purchaseAddressService = $purchaseAddressService;
        $this->cartService = $cartService;
    }

    /**
     * Formulaire de coordonnées à stocker dans la session.
     * 
     * @Route("/commande/informations", name="purchase_info")
     */
    public function info(Request $request): Response
    {
        // Si le panier est vide, on dégage !
        if ($this->cartService->isEmpty()) return $this->redirectToRoute('accueil');

        $form = $this->createForm(PurchaseAddressType::class, $this->purchaseAddressService->get());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $data = $form->getData();

            $this->purchaseAddressService->set($data);

            return $this->redirectToRoute('purchase_payment', [
                'cgvBool' => '0',
            ]);
        }

        return $this->renderForm('purchase/info.html.twig', [
            'formView' => $form
        ]);
    }

    /**
     * Récapitulatif de la commande avant paiement via Stripe
     * 
     * @Route("/commande/confirmation/cgv={cgvBool}", name="purchase_payment")
     */
    public function purchaseConfirmation(bool $cgvBool, ShippingCostService $shippingCostService): Response
    {
        // Si le panier est vide, on dégage !
        if ($this->cartService->isEmpty()) return $this->redirectToRoute('accueil');

        $total = $this->cartService->getTotal();
        $shippingCost = $shippingCostService->getShippingCost($this->cartService);

        return $this->render('purchase/confirmation.html.twig', [
            'purchaseAddresses' => $this->purchaseAddressService->get(),
            'cart' => $this->cartService->getDetailedCartItems(),
            'insuranceCost' => $shippingCost->getInsurance(),
            'weightCost' => $shippingCost->getWeightCost(),
            'totalProducts' => $total,
            'totalOfTotal' => $total + $shippingCost->getInsurance() + $shippingCost->getWeightCost(),
            'cgvBool' => $cgvBool ? true : false,
        ]);
    }

    /**
     * @Route("/cgv", name="cgv")
     */
    public function cgv(): Response
    {
        $cgv = $this->appSettingsRepo->findAll()[0]->getCgv();

        return $this->render('purchase/cgv.html.twig', [
            'cgv' => $cgv
        ]);
    }
}

templates/purchase/cgv.html.twig
{{ cgv | raw  }}

templates/purchase/confirmation.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Confirmation de votre commande |
	{{ parent() }}
{% endblock %}

{% block description %}
	Panier de mes produits sélectionnés
{% endblock %}

{% block body %}

	<h2>
		<span class="lettrine lettrine-title">C</span>onfirmation</h2>

	{% if cgvBool == true %}
		<p class="mb-2 invalide para center no-indent bolder">
			Vous devez accepter les conditions générales de vente !
		</p>
	{% endif %}

	<div class="bolder para center no-indent larger">Récapitulatif de votre commande</div>

	<div class="bolder para center no-indent larger">Adresse et coordonnées</div>

	<div class="para center no-indent mb-2">
		<p>
			<a class="link" href="{{ path('purchase_info') }}">Modifier</a>
		</p>

		<div class="{% if purchaseAddresses.hasBillingAddress %}mb-1{% endif %}">
			{% if purchaseAddresses.hasBillingAddress %}
				<p class="bolder">Adresse de facturation</p>
			{% endif %}
			<p>{{ purchaseAddresses.email }}</p>
			<p>{{ purchaseAddresses.firstAddressFullname }}</p>
			<p>{{ purchaseAddresses.firstAddressAddress }}</p>
			<p>{{ purchaseAddresses.firstAddressPostalCode }}
				{{ purchaseAddresses.firstAddressCity }},
				{{ purchaseAddresses.firstAddressCountry | country_name('fr')}}</p>
			<p>{{ purchaseAddresses.firstAddressPhone }}</p>
		</div>

		{% if purchaseAddresses.hasBillingAddress %}
			<div>
				<p class="bolder">Adresse de livraison</p>
				<p>{{ purchaseAddresses.secondAddressFullname }}</p>
				<p>{{ purchaseAddresses.secondAddressAddress }}</p>
				<p>{{ purchaseAddresses.secondAddressPostalCode }}
					{{ purchaseAddresses.secondAddressCity }},
					{{ purchaseAddresses.secondAddressCountry | country_name('fr')}}</p>
			</div>
		{% endif %}
	</div>

	<div class="bolder para center no-indent larger">Vos articles</div>

	<div class="para center no-indent mb-2">
		<p>
			<a class="js-open-modal-cart link" validate-url="{{ path('purchase_payment', {cgvBool: '0'}) }}" style="cursor: pointer;">Modifier</a>
		</p>
		<div class="flex-list">
			<ul class="para list">
				{% for item in cart %}
					<li class="no-list-style left" style="display: flex; align-items: center; margin-bottom: 10px; border: 1px solid rgb(190, 190, 190); padding: 10px; border-radius: 2px;">
						{% set src = httpToHttps(vich_uploader_asset(item.product.firstImage, item.product.firstImage.imageWatermarked ? 'imageWatermarkedFile' : 'imageOriginalFile') | imagine_filter('boutique_mini')) %}
						<img style="height: 80px; width: 80px; object-fit: contain;" src="{{ src }}" alt="{{ item.product.__toString }}"/>
						<div>
							<p>{{ item.product.__toString}}</p>
							<p>{{ item.qty }}
								x
								{{ item.product.price | amount }}
								=
								{{ (item.qty * item.product.price) | amount }}
							</p>
						</div>
					</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class=" para center no-indent">
		<p>Total produits :
			{{ totalProducts | amount }}</p>
		<p>Frais d'assurance :
			{{ insuranceCost | amount }}</p>
		<p>Frais de port :
			{{ weightCost | amount }}</p>
	</div>

	<div class="bolder para center no-indent">
		<p>TOTAL TTC :
			{{ totalOfTotal | amount }}</p>
	</div>

	<div class="bolder para center no-indent mb-2">
		<p class="mb-1">
			<input type="checkbox" id="js-accept-cgv">
			Vous avez lu et accepté les
			<a class="link" target="_blank" href="{{ path('cgv') }}">conditions générales de vente</a>.
		</p>
		{% if cgvBool == true %}
			<p class="mb-2 invalide">
				Vous devez accepter les conditions générales de vente !
			</p>
		{% endif %}
		<p class="mb-1">
			<a id="js-stripe-pay-link" class="pay-button" payment-url="{{ path('payment_index')}}" href="{{ path('purchase_payment', {'cgvBool': '1'}) }}">Procéder au paiement</a>
		</p>
	</div>

{% endblock %}

templates/purchase/info.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Commande |
	{{ parent() }}
{% endblock %}

{% block description %}
	Panier de mes produits sélectionnés
{% endblock %}

{% block body %}
	<h2>
		<span class="lettrine lettrine-title">I</span>nformations</h2>

	<div class="para center no-indent">
		Entrez vos coordonnées de livraison :
	</div>

	{{ form_start(formView) }}

	<div class="first-address">
		{{ form_row(formView.email)}}
		{{ form_row(formView.firstAddressFullname)}}
		{{ form_row(formView.firstAddressAddress)}}
		{{ form_row(formView.firstAddressPostalCode)}}
		{{ form_row(formView.firstAddressCity)}}
		{{ form_row(formView.firstAddressCountry)}}
		{{ form_row(formView.firstAddressPhone)}}
	</div>
	<div class="has-billing-address">
		{{ form_row(formView.hasBillingAddress)}}
	</div>
	<div class="second-address" style="display: {% if formView.hasBillingAddress.vars.data == true %}flex;{% else %}none;{% endif %}">
		{{ form_row(formView.secondAddressFullname)}}
		{{ form_row(formView.secondAddressAddress)}}
		{{ form_row(formView.secondAddressPostalCode)}}
		{{ form_row(formView.secondAddressCity)}}
		{{ form_row(formView.secondAddressCountry)}}
	</div>

	<div>
		<button type="submit" class="pay-button mt-4" style="cursor: pointer">Valider mes informations</button>
	</div>
	{{ form_end(formView) }}


{% endblock %}